name: Python build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run black
        uses: psf/black@stable

  lint:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Include `--format=github` to enable automatic inline annotations.
      - name: run ruff
        run: ruff check --output-format=github .

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python }}
          auto-activate-base: false
      - name: install dependencies
        run: ./prepare-env.sh ${{ matrix.python }} seutil
      - name: run unit tests
        run: |
          eval "$(conda shell.bash hook)"
          conda activate seutil
          pytest tests/unit --cov-report=term-missing --cov-append
      - name: setup env for integration tests - texlive
        uses: teatimeguest/setup-texlive-action@v3.3.0
        with:
          version: 2023
          packages: scheme-full
      - name: run integration tests
        run: |
          eval "$(conda shell.bash hook)"
          conda activate seutil
          pytest tests/integration --cov-report=term-missing --cov-append

  test-quick:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python }}
          auto-activate-base: false
      - name: install dependencies (w/o optional dependencies)
        run: ./prepare-env.sh ${{ matrix.python }} seutil false
      - name: run unit tests
        run: |
          eval "$(conda shell.bash hook)"
          conda activate seutil
          pytest tests/unit --cov-report=term-missing --cov-append
